service: event-service
package:
  version: 0.0.1-SNAPSHOT
  artifact: ./application/target/${self:service}-${self:package.version}-${self:provider}.jar
provider:
  name: aws
  runtime: java11
  region: us-east-2
  memorySize: 1024
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"
  environment:
    APPLICATION_ENVIRONMENT: Dev
    CLOUD_REGION: US_East_2
functions:
  creatEvent:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: event/create
          method: post
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: createFunction
  updateEvent:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: event/update
          method: post
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: updateFunction
  disableEvent:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: event/disable
          method: post
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: disableFunction
  getEvent:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: event/findById
          method: post
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: getFunction

resources:
  Resources:
    productsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Event
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
          - AttributeName: eventDate
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
          - AttributeName: eventDate
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1